insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (101, '8098 Commercial Crossing');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (102, '63 Aberg Drive');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (103, '378 Golf Course Place');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (104, '107 Basil Road');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (105, '22404 American Ash Parkway');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (106, '36521 Moland Drive');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (107, '6211 Arizona Terrace');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (108, '3 Mayfield Alley');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (109, '64 Grayhawk Way');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (110, '6270 Mifflin Alley');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (111, '8 Melody Alley');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (112, '94003 Coleman Plaza');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (113, '8 Larry Crossing');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (114, '82 Norway Maple Avenue');
insert into BIBLIOTECA.Funcionario (id_funcionario, morada) values (115, '118 Village Plaza');
