INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Bogan-Grimes','4 Sachtjen Court',955362012);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Murray-Morissette','0705 Texas Terrace',930040562);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Schmeler, Zemlak and Kohler','596 Dennis Court',927328694);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Dibbert, Dare and Mayer','588 Canary Lane',908268831);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Kuvalis Inc','31651 Mallard Place',919012828);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Rolfson and Sons','62 Dahle Hill',926540390);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Abernathy, Walter and Fisher','724 Union Lane',933456730);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Simonis, Spinka and Wintheiser','086 Mcbride Road',911499579);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Grant, Tillman and Mayert','3 Tennyson Point',946988801);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Haley Inc','6 Buena Vista Terrace',925540548);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Veum, Hirthe and Doyle','63 Holmberg Hill',994795335);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Gulgowski-Spinka','48 Merchant Street',971721059);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Kuhn-Hansen','9 2nd Terrace',996373771);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Witting-Morar','8 Valley Edge Circle',923445900);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Hansen-Mosciski','8665 Warner Terrace',985996379);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Hilll-Hyatt','36 Waywood Avenue',951763122);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Rau and Sons','4156 Anzinger Way',950156002);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Torp LLC','644 Mayer Trail',925777299);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Wilkinson, Tillman and Bergstrom','5 Merrick Way',952657513);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Weissnat-Volkman','690 Kennedy Pass',906459317);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Dibbert-Bernier','7 Riverside Alley',900789733);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Kulas Group','2 Artisan Crossing',971675952);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Keeling and Sons','07 Mallard Road',912790569);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Lemke-Thompson','6 Valley Edge Drive',957953837);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Mitchell-Schmidt','2291 Grover Terrace',925763284);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Medhurst LLC','3 Lien Parkway',976993833);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('O''Connell Inc','59614 Corry Road',905328882);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Grimes-Parker','351 Westport Center',936176616);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Keebler-Herman','09 Surrey Point',923874273);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('VonRueden, Kuvalis and Hilll','5 Twin Pines Terrace',974457096);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Jenkins-Farrell','49006 Ronald Regan Way',910139920);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Kulas-Mueller','07 Washington Parkway',954660415);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Crona-Mohr','00427 Crest Line Trail',989934269);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Gutkowski-Romaguera','01249 Magdeline Point',911457309);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Trantow, Kautzer and Tromp','4 Trailsway Parkway',974562922);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Metz Group','18722 Spohn Plaza',994731882);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Fadel-Weissnat','447 Blaine Park',941536604);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Ortiz-Olson','75 Michigan Point',920751641);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Kovacek Group','58 Vera Lane',966182740);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Hackett-Huel','99 Katie Alley',936006281);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Orn-Grant','4 Forest Run Way',913604416);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Kohler-Will','6262 Ludington Crossing',903727161);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Grant-Marvin','61 Pond Avenue',912713527);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Haag, Williamson and Hoppe','90355 Surrey Drive',938175909);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('McCullough-Raynor','249 Magdeline Point',943670872);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Funk Group','2 Kingsford Court',995936779);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Shanahan Group','239 1st Point',950981386);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Bins-Boyer','8835 Fallview Way',905411532);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Beatty-Wintheiser','51912 Corscot Lane',916681823);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Effertz, Zulauf and Kiehn','7 Almo Plaza',927550975);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Schroeder LLC','16 Kensington Park',979613279);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Jones, Hagenes and Mayer','3709 Mayer Parkway',931630945);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Labadie LLC','63166 Banding Street',903561251);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Dooley Group','274 Carberry Pass',975273517);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Terry LLC','5378 Hollow Ridge Junction',922134457);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Harris, Volkman and Simonis','1161 Lakeland Pass',933915526);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Von Group','33 Scott Parkway',926589401);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Jaskolski, Kling and Barton','484 Surrey Center',979961548);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Gerlach Inc','57886 Kensington Point',975034823);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Strosin, Stehr and Hettinger','0536 Loftsgordon Way',980484274);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Larkin, Johnston and Bayer','6154 Division Parkway',927395964);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Schimmel-Koelpin','010 Fairfield Terrace',980107905);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Ryan-Kozey','13 Packers Circle',919385209);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Kertzmann and Sons','8 Pearson Place',945883655);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Gulgowski LLC','56 Meadow Valley Junction',931980827);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Green Inc','8496 Randy Park',978823338);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Feil-King','9 Goodland Circle',970495136);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Klein, Watsica and Beatty','22 Del Mar Avenue',982436663);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Watsica Inc','1 Spaight Plaza',918516040);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Shields-Crooks','4 Brickson Park Alley',917600151);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Fritsch-Dickens','2 Kings Lane',927188921);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Carroll and Sons','51 Vidon Way',934827432);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Beatty, Murray and Stark','20604 Hazelcrest Park',975431146);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Hessel-Lemke','04617 Fremont Point',968973153);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Tillman-Gibson','22 Reinke Road',915589703);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Greenholt and Sons','98 Ridgeway Road',918747415);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Robel, Collins and Hudson','490 Waxwing Road',925494254);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Collier and Sons','3 Lien Center',979454497);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Schmeler Inc','9083 Bonner Parkway',913723170);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Schultz, Wolff and Dibbert','5 Brown Circle',919908405);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Murphy-Huels','8 Luster Plaza',901153149);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Sporer, Green and Cole','633 Muir Plaza',977406146);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Mosciski, Rutherford and Considine','7874 Valley Edge Circle',999488756);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Kreiger-Ullrich','5975 Morningstar Center',952807835);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Ortiz-Spencer','739 Stephen Park',927448627);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Jaskolski, Jenkins and Leuschke','7 Straubel Way',956495404);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Jast, Krajcik and McGlynn','65283 Schurz Court',993639729);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Heidenreich LLC','425 Crownhardt Road',964875781);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Corwin, Zemlak and Boyer','7 Cambridge Plaza',922652728);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Gerlach-Hodkiewicz','15 Lotheville Plaza',925093004);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Gislason, Durgan and Mitchell','9 Huxley Crossing',990247033);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Krajcik, Ratke and Kreiger','0333 6th Court',935291942);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Pfeffer, Wolf and Littel','15802 Mockingbird Hill',914566566);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Fisher-Schamberger','228 Grim Circle',991002427);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Corwin-Tremblay','4906 Pleasure Parkway',900680023);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Harvey, Beer and Bergnaum','0477 Warrior Alley',981261932);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Roberts Group','36 Miller Center',903830853);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Crist, Breitenberg and Quigley','9 Moulton Alley',952247942);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Runte-Krajcik','1 Anhalt Pass',919228009);
INSERT INTO BIBLIOTECA.Editora(nome_editora,endereco,telefone) VALUES ('Treutel, Breitenberg and Gerhold','7 Scoville Court',944592605);