INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (1,'Bogan-Grimes','4 Sachtjen Court',955362012);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (2,'Murray-Morissette','0705 Texas Terrace',930040562);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (3,'Schmeler, Zemlak and Kohler','596 Dennis Court',927328694);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (4,'Dibbert, Dare and Mayer','588 Canary Lane',908268831);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (5,'Kuvalis Inc','31651 Mallard Place',919012828);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (6,'Rolfson and Sons','62 Dahle Hill',926540390);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (7,'Abernathy, Walter and Fisher','724 Union Lane',933456730);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (8,'Simonis, Spinka and Wintheiser','086 Mcbride Road',911499579);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (9,'Grant, Tillman and Mayert','3 Tennyson Point',946988801);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (10,'Haley Inc','6 Buena Vista Terrace',925540548);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (11,'Veum, Hirthe and Doyle','63 Holmberg Hill',994795335);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (12,'Gulgowski-Spinka','48 Merchant Street',971721059);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (13,'Kuhn-Hansen','9 2nd Terrace',996373771);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (14,'Witting-Morar','8 Valley Edge Circle',923445900);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (15,'Hansen-Mosciski','8665 Warner Terrace',985996379);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (16,'Hilll-Hyatt','36 Waywood Avenue',951763122);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (17,'Rau and Sons','4156 Anzinger Way',950156002);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (18,'Torp LLC','644 Mayer Trail',925777299);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (19,'Wilkinson, Tillman and Bergstrom','5 Merrick Way',952657513);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (20,'Weissnat-Volkman','690 Kennedy Pass',906459317);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (21,'Dibbert-Bernier','7 Riverside Alley',900789733);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (22,'Kulas Group','2 Artisan Crossing',971675952);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (23,'Keeling and Sons','07 Mallard Road',912790569);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (24,'Lemke-Thompson','6 Valley Edge Drive',957953837);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (25,'Mitchell-Schmidt','2291 Grover Terrace',925763284);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (26,'Medhurst LLC','3 Lien Parkway',976993833);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (27,'O''Connell Inc','59614 Corry Road',905328882);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (28,'Grimes-Parker','351 Westport Center',936176616);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (29,'Keebler-Herman','09 Surrey Point',923874273);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (30,'VonRueden, Kuvalis and Hilll','5 Twin Pines Terrace',974457096);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (31,'Jenkins-Farrell','49006 Ronald Regan Way',910139920);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (32,'Kulas-Mueller','07 Washington Parkway',954660415);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (33,'Crona-Mohr','00427 Crest Line Trail',989934269);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (34,'Gutkowski-Romaguera','01249 Magdeline Point',911457309);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (35,'Trantow, Kautzer and Tromp','4 Trailsway Parkway',974562922);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (36,'Metz Group','18722 Spohn Plaza',994731882);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (37,'Fadel-Weissnat','447 Blaine Park',941536604);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (38,'Ortiz-Olson','75 Michigan Point',920751641);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (39,'Kovacek Group','58 Vera Lane',966182740);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (40,'Hackett-Huel','99 Katie Alley',936006281);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (41,'Orn-Grant','4 Forest Run Way',913604416);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (42,'Kohler-Will','6262 Ludington Crossing',903727161);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (43,'Grant-Marvin','61 Pond Avenue',912713527);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (44,'Haag, Williamson and Hoppe','90355 Surrey Drive',938175909);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (45,'McCullough-Raynor','249 Magdeline Point',943670872);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (46,'Funk Group','2 Kingsford Court',995936779);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (47,'Shanahan Group','239 1st Point',950981386);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (48,'Bins-Boyer','8835 Fallview Way',905411532);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (49,'Beatty-Wintheiser','51912 Corscot Lane',916681823);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (50,'Effertz, Zulauf and Kiehn','7 Almo Plaza',927550975);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (51,'Schroeder LLC','16 Kensington Park',979613279);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (52,'Jones, Hagenes and Mayer','3709 Mayer Parkway',931630945);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (53,'Labadie LLC','63166 Banding Street',903561251);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (54,'Dooley Group','274 Carberry Pass',975273517);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (55,'Terry LLC','5378 Hollow Ridge Junction',922134457);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (56,'Harris, Volkman and Simonis','1161 Lakeland Pass',933915526);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (57,'Von Group','33 Scott Parkway',926589401);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (58,'Jaskolski, Kling and Barton','484 Surrey Center',979961548);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (59,'Gerlach Inc','57886 Kensington Point',975034823);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (60,'Strosin, Stehr and Hettinger','0536 Loftsgordon Way',980484274);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (61,'Larkin, Johnston and Bayer','6154 Division Parkway',927395964);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (62,'Schimmel-Koelpin','010 Fairfield Terrace',980107905);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (63,'Ryan-Kozey','13 Packers Circle',919385209);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (64,'Kertzmann and Sons','8 Pearson Place',945883655);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (65,'Gulgowski LLC','56 Meadow Valley Junction',931980827);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (66,'Green Inc','8496 Randy Park',978823338);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (67,'Feil-King','9 Goodland Circle',970495136);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (68,'Klein, Watsica and Beatty','22 Del Mar Avenue',982436663);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (69,'Watsica Inc','1 Spaight Plaza',918516040);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (70,'Shields-Crooks','4 Brickson Park Alley',917600151);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (71,'Fritsch-Dickens','2 Kings Lane',927188921);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (72,'Carroll and Sons','51 Vidon Way',934827432);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (73,'Beatty, Murray and Stark','20604 Hazelcrest Park',975431146);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (74,'Hessel-Lemke','04617 Fremont Point',968973153);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (75,'Tillman-Gibson','22 Reinke Road',915589703);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (76,'Greenholt and Sons','98 Ridgeway Road',918747415);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (77,'Robel, Collins and Hudson','490 Waxwing Road',925494254);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (78,'Collier and Sons','3 Lien Center',979454497);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (79,'Schmeler Inc','9083 Bonner Parkway',913723170);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (80,'Schultz, Wolff and Dibbert','5 Brown Circle',919908405);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (81,'Murphy-Huels','8 Luster Plaza',901153149);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (82,'Sporer, Green and Cole','633 Muir Plaza',977406146);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (83,'Mosciski, Rutherford and Considine','7874 Valley Edge Circle',999488756);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (84,'Kreiger-Ullrich','5975 Morningstar Center',952807835);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (85,'Ortiz-Spencer','739 Stephen Park',927448627);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (86,'Jaskolski, Jenkins and Leuschke','7 Straubel Way',956495404);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (87,'Jast, Krajcik and McGlynn','65283 Schurz Court',993639729);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (88,'Heidenreich LLC','425 Crownhardt Road',964875781);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (89,'Corwin, Zemlak and Boyer','7 Cambridge Plaza',922652728);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (90,'Gerlach-Hodkiewicz','15 Lotheville Plaza',925093004);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (91,'Gislason, Durgan and Mitchell','9 Huxley Crossing',990247033);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (92,'Krajcik, Ratke and Kreiger','0333 6th Court',935291942);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (93,'Pfeffer, Wolf and Littel','15802 Mockingbird Hill',914566566);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (94,'Fisher-Schamberger','228 Grim Circle',991002427);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (95,'Corwin-Tremblay','4906 Pleasure Parkway',900680023);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (96,'Harvey, Beer and Bergnaum','0477 Warrior Alley',981261932);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (97,'Roberts Group','36 Miller Center',903830853);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (98,'Crist, Breitenberg and Quigley','9 Moulton Alley',952247942);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (99,'Runte-Krajcik','1 Anhalt Pass',919228009);
INSERT INTO BIBLIOTECA.Editora(id_editora,nome_editora,endereco,telefone) VALUES (100,'Treutel, Breitenberg and Gerhold','7 Scoville Court',944592605);